version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: "healthy-db"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/:ro,z
    env_file:
      - .env-postgres
    environment:
      POSTGRES_DB: healthy-db
      POSTGRES_PASSWORD: 123facil
      POSTGRES_USER: cristiandpt
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
