INSERT INTO specialties (name, description, tenant_id, is_active, image_url, is_doctor_managed_rate, consultation_rate, video_call_rate, video_call_minutes) VALUES
('General Medicine', 'Provides comprehensive healthcare for individuals and families across all ages, focusing on prevention, diagnosis, and treatment of common illnesses.', 1, TRUE, 'https://example.com/images/generalmedicine.jpg', FALSE, 180.00, 150.00, 20),
('Cardiology', 'Diagnosis and treatment of heart conditions and blood vessels.', 1, TRUE, 'https://example.com/images/cardiology.jpg', FALSE, 300.00, 250.00, 30),
('Pediatrics', 'Medical care for infants, children, and adolescents.', 1, TRUE, 'https://example.com/images/pediatrics.jpg', FALSE, 200.00, 170.00, 25),
('Dermatology', 'Diagnosis and treatment of skin, hair, and nail disorders.', 1, TRUE, 'https://example.com/images/dermatology.jpg', TRUE, 250.00, 210.00, 20),
('Orthopedics', 'Diagnosis and treatment of musculoskeletal system disorders.', 1, TRUE, 'https://example.com/images/orthopedics.jpg', FALSE, 350.00, 290.00, 30),
('Neurology', 'Diagnosis and treatment of nervous system disorders.', 1, TRUE, 'https://example.com/images/neurology.jpg', FALSE, 320.00, 270.00, 35),
('Gastroenterology', 'Diagnosis and treatment of digestive system disorders.', 1, TRUE, 'https://example.com/images/gastroenterology.jpg', TRUE, 280.00, 230.00, 25),
('Ophthalmology', 'Diagnosis and treatment of eye diseases and vision problems.', 1, TRUE, 'https://example.com/images/ophthalmology.jpg', FALSE, 240.00, 200.00, 20),
('Otolaryngology (ENT)', 'Diagnosis and treatment of ear, nose, and throat conditions.', 1, TRUE, 'https://example.com/images/ent.jpg', FALSE, 260.00, 220.00, 25),
('Gynecology', 'Medical care for women, particularly reproductive health.', 1, TRUE, 'https://example.com/images/gynecology.jpg', FALSE, 230.00, 190.00, 25),
('Urology', 'Diagnosis and treatment of urinary tract and male reproductive system disorders.', 1, TRUE, 'https://example.com/images/urology.jpg', TRUE, 290.00, 240.00, 30),
('Psychiatry', 'Diagnosis, treatment, and prevention of mental, emotional, and behavioral disorders.', 1, TRUE, 'https://example.com/images/psychiatry.jpg', FALSE, 380.00, 320.00, 45),
('Endocrinology', 'Diagnosis and treatment of hormone-related conditions and glandular disorders.', 1, TRUE, 'https://example.com/images/endocrinology.jpg', FALSE, 270.00, 225.00, 30),
('Oncology', 'Diagnosis and treatment of cancer.', 1, TRUE, 'https://example.com/images/oncology.jpg', FALSE, 450.00, 380.00, 40),
('Pulmonology', 'Diagnosis and treatment of lung and respiratory system disorders.', 1, TRUE, 'https://example.com/images/pulmonology.jpg', TRUE, 250.00, 205.00, 25),
('Rheumatology', 'Diagnosis and treatment of musculoskeletal disease and systemic autoimmune conditions.', 1, TRUE, 'https://example.com/images/rheumatology.jpg', FALSE, 280.00, 230.00, 30),
('Nephrology', 'Diagnosis and treatment of kidney diseases.', 1, TRUE, 'https://example.com/images/nephrology.jpg', FALSE, 290.00, 240.00, 30),
('General Surgery', 'Performs surgical procedures to treat injuries, diseases, and deformities.', 1, TRUE, 'https://example.com/images/generalsurgery.jpg', FALSE, 340.00, 280.00, 30),
('Anesthesiology', 'Administers anesthesia for surgery and provides pain management.', 1, TRUE, 'https://example.com/images/anesthesiology.jpg', TRUE, 300.00, 250.00, 20),
('Emergency Medicine', 'Provides immediate care for acute illnesses and injuries.', 1, TRUE, 'https://example.com/images/emergencymedicine.jpg', FALSE, 320.00, 270.00, 20),
('Radiology', 'Uses imaging techniques to diagnose and treat diseases.', 1, TRUE, 'https://example.com/images/radiology.jpg', FALSE, 180.00, 150.00, 15);
