spring:
  application:
    name: infrastructure-app

api:
  auth:
    base-path: /api/authentication/account
    login: /login
    login-facebook: /login/facebook
    login-google: /login/google
    social-register: /social-register
    register: /register
